Repository i3drobotics/pyphase, pull requests merged in 2022-08, with the labels that each got.

#30 marked missing doc in code
  src/bindings/calib/cameracalibration_bindings.cpp
  src/bindings/calib/stereocalibration_bindings.cpp
  src/bindings/phaseversion_bindings.cpp
  src/bindings/rgbdvideostream_bindings.cpp
  src/bindings/rgbdvideowriter_bindings.cpp
  src/bindings/stereocamera/abstractstereocamera_bindings.cpp
  src/bindings/stereocamera/deimosstereocamera_bindings.cpp
  src/bindings/stereocamera/phobosstereocamera_bindings.cpp
  src/bindings/stereocamera/pylonstereocamera_bindings.cpp
  src/bindings/stereocamera/stereocamera_bindings.cpp
  src/bindings/stereocamera/titaniastereocamera_bindings.cpp
  src/bindings/stereocamera/uvcstereocamera_bindings.cpp
  src/bindings/stereomatcher/abstractstereomatcher_bindings.cpp
  src/bindings/stereomatcher/stereobm_bindings.cpp
  src/bindings/stereomatcher/stereohobm_bindings.cpp
  src/bindings/stereomatcher/stereoi3drsgm_bindings.cpp
  src/bindings/stereomatcher/stereomatcher_bindings.cpp
  src/bindings/stereomatcher/stereosgbm_bindings.cpp
  src/bindings/stereoprocess_bindings.cpp
  src/bindings/stereovision_bindings.cpp
  src/bindings/types/cameradeviceinfo_bindings.cpp
  src/bindings/types/common_bindings.cpp
  src/bindings/types/mat_bindings.cpp
  src/bindings/utils_bindings.cpp
  test/drivers/demo_match.py
  test/drivers/demo_match_thread.py
  test/drivers/demo_read.py
  test/drivers/demo_read_thread.py
  test/drivers/demo_rgbd.py
  test/src/calib/test_cameracalibration.py
  test/src/calib/test_stereocalibration.py
  test/src/stereocamera/test_abstractstereocamera.py
  test/src/stereocamera/test_pylonstereocamera.py
  test/src/stereocamera/test_stereocamera.py
  test/src/stereocamera/test_uvcstereocamera.py
  test/src/stereomatcher/test_stereobm.py
  test/src/stereomatcher/test_stereoi3drsgm.py
  test/src/stereomatcher/test_stereomatcher.py
  test/src/stereomatcher/test_stereosgbm.py
  test/src/test_rgbdvideostream.py
  test/src/test_rgbdvideowriter.py
  test/src/test_stereovision.py
  test/src/test_utils.py
  test/src/types/test_cameradeviceinfo.py
  test/src/types/test_common.py
  test/src/types/test_mat.py
Labels: documentation

#32 Gitpod phase docker install
  .gitpod.Dockerfile
  .gitpod.yml
Labels: enhancement

#31 Add code docs
  docs/sphinx/conf.py
  requirements.txt
  src/bindings/calib/cameracalibration_bindings.cpp
  src/bindings/calib/stereocalibration_bindings.cpp
  src/bindings/phaseversion_bindings.cpp
  src/bindings/rgbdvideostream_bindings.cpp
  src/bindings/rgbdvideowriter_bindings.cpp
  src/bindings/stereocamera/abstractstereocamera_bindings.cpp
  src/bindings/stereocamera/deimosstereocamera_bindings.cpp
  src/bindings/stereocamera/phobosstereocamera_bindings.cpp
  src/bindings/stereocamera/pylonstereocamera_bindings.cpp
  src/bindings/stereocamera/stereocamera_bindings.cpp
  src/bindings/stereocamera/titaniastereocamera_bindings.cpp
  src/bindings/stereocamera/uvcstereocamera_bindings.cpp
  src/bindings/stereomatcher/abstractstereomatcher_bindings.cpp
  src/bindings/stereomatcher/stereobm_bindings.cpp
  src/bindings/stereomatcher/stereohobm_bindings.cpp
  src/bindings/stereomatcher/stereoi3drsgm_bindings.cpp
  src/bindings/stereomatcher/stereomatcher_bindings.cpp
  src/bindings/stereomatcher/stereosgbm_bindings.cpp
  src/bindings/stereoprocess_bindings.cpp
  src/bindings/stereovision_bindings.cpp
  src/bindings/types/cameradeviceinfo_bindings.cpp
  src/bindings/types/common_bindings.cpp
  src/bindings/types/mat_bindings.cpp
  src/bindings/utils_bindings.cpp
  test/src/calib/test_cameracalibration.py
  test/src/calib/test_stereocalibration.py
  test/src/stereocamera/test_abstractstereocamera.py
  test/src/stereocamera/test_pylonstereocamera.py
  test/src/stereocamera/test_stereocamera.py
  test/src/stereocamera/test_uvcstereocamera.py
  test/src/stereomatcher/test_abstractstereomatcher.py
  test/src/stereomatcher/test_stereobm.py
  test/src/stereomatcher/test_stereoi3drsgm.py
  test/src/stereomatcher/test_stereomatcher.py
  test/src/stereomatcher/test_stereosgbm.py
  test/src/test_rgbdvideostream.py
  test/src/test_rgbdvideowriter.py
  test/src/test_stereovision.py
  test/src/test_utils.py
  test/src/types/test_cameradeviceinfo.py
  test/src/types/test_common.py
  test/src/types/test_mat.py
Labels: documentation

#33 add prerelease
  .github/workflows/release.yml
  CMakeLists.txt
Labels: enhancement

#35 Upgrade phase 0.0.27-1
  .github/workflows/build.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .gitpod.Dockerfile
  README.md
  docs/README_developer.md
Labels: bug

#36 Upgrade phase 0.1.2-10
  .github/workflows/build.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .gitpod.Dockerfile
  README.md
  docs/README_developer.md
  src/bindings/pyphase_bindings.cpp
  src/bindings/rgbdvideostream_bindings.cpp
  src/bindings/rgbdvideowriter_bindings.cpp
  src/bindings/stereomatcher/stereohobm_bindings.cpp
  src/bindings/stereoprocess_bindings.cpp
  src/bindings/stereovision_bindings.cpp
  src/bindings/types/common_bindings.cpp
  src/package/phase/__init__.py
  test/src/test_rgbdvideostream.py
  test/src/test_rgbdvideowriter.py
  test/src/test_stereovision.py
  test/src/test_utils.py
  test/src/types/test_common.py
Labels: enhancement

#37 Upgrade phase 0.1.2 11
  .github/workflows/build.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .gitpod.Dockerfile
  README.md
  docs/README_developer.md
  src/bindings/calib/cameracalibration_bindings.cpp
  src/bindings/calib/stereocalibration_bindings.cpp
  src/bindings/pyphase_bindings.cpp
  src/bindings/stereocamera/abstractstereocamera_bindings.cpp
  src/bindings/stereomatcher/abstractstereomatcher_bindings.cpp
  src/bindings/types/cameradeviceinfo_bindings.cpp
  src/bindings/types/common_bindings.cpp
  src/bindings/types/stereo_bindings.cpp
  test/src/stereocamera/test_abstractstereocamera.py
  test/src/stereocamera/test_cameradeviceinfo.py
  test/src/stereocamera/test_pylonstereocamera.py
  test/src/stereocamera/test_stereocamera.py
  test/src/stereocamera/test_uvcstereocamera.py
  test/src/stereomatcher/test_stereomatcher.py
  test/src/test_utils.py
  test/src/types/test_cameradeviceinfo.py
  test/src/types/test_stereo.py
Labels: enhancement

#38 upgrade to phase v0.1.2-12
  .github/workflows/build.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .gitpod.Dockerfile
  README.md
  docs/README_developer.md
Labels: enhancement

#39 Upgrade phase 0.1.2-13
  .github/workflows/build.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .gitpod.Dockerfile
  CMakeLists.txt
  README.md
  docs/README_developer.md
Labels: enhancement

#40 Upgrade Phase 0.1.2-14
  .github/workflows/build.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  .gitpod.Dockerfile
  README.md
  docs/README_developer.md
  src/bindings/pyphase_bindings.cpp
  src/bindings/stereocamera/cameradeviceinfo_bindings.cpp
  src/bindings/utils_bindings.cpp
  src/bindings/version_bindings.cpp
  test/drivers/demo_rgbd.py
Labels: enhancement

#44 Improve docs
  src/bindings/calib/cameracalibration_bindings.cpp
  src/bindings/calib/stereocalibration_bindings.cpp
  src/bindings/pyphase_bindings.cpp
  src/bindings/stereocamera/abstractstereocamera_bindings.cpp
  src/bindings/stereocamera/deimosstereocamera_bindings.cpp
  src/bindings/stereocamera/phobosstereocamera_bindings.cpp
  src/bindings/stereocamera/pylonstereocamera_bindings.cpp
  src/bindings/stereocamera/titaniastereocamera_bindings.cpp
  src/bindings/stereocamera/uvcstereocamera_bindings.cpp
  src/bindings/stereomatcher/abstractstereomatcher_bindings.cpp
  src/bindings/stereomatcher/stereobm_bindings.cpp
  src/bindings/stereomatcher/stereoi3drsgm_bindings.cpp
  src/bindings/stereomatcher/stereomatcher_bindings.cpp
  src/bindings/stereomatcher/stereosgbm_bindings.cpp
  src/bindings/types/mat_bindings.cpp
  src/bindings/types/stereo_bindings.cpp
  src/bindings/version_bindings.cpp
Labels: documentation

#43 Perf test
  .github/workflows/build.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  README.md
  src/bindings/types/mat_bindings.cpp
  test/perf/calib/test_cameracalibration.py
  test/perf/calib/test_stereocalibration.py
  test/perf/stereocamera/test_cameradeviceinfo.py
  test/perf/stereocamera/test_deimosstereocamera.py
  test/perf/stereocamera/test_phobosstereocamera.py
  test/perf/stereocamera/test_pylonstereocamera.py
  test/perf/stereocamera/test_stereocamera.py
  test/perf/stereocamera/test_titaniastereocamera.py
  test/perf/stereocamera/test_uvcstereocamera.py
  test/perf/stereomatcher/test_stereobm.py
  test/perf/stereomatcher/test_stereoi3drsgm.py
  test/perf/stereomatcher/test_stereosgbm.py
  test/perf/test_utils.py
  test/perf/types/test_mat.py
  test/perf/types/test_stereo.py
  test/src/types/test_mat.py
  test/src/types/test_stereo.py
  test/unit/calib/test_cameracalibration.py
  test/unit/calib/test_stereocalibration.py
  test/unit/stereocamera/test_abstractstereocamera.py
  test/unit/stereocamera/test_cameradeviceinfo.py
  test/unit/stereocamera/test_deimosstereocamera.py
  test/unit/stereocamera/test_phobosstereocamera.py
  test/unit/stereocamera/test_pylonstereocamera.py
  test/unit/stereocamera/test_stereocamera.py
  test/unit/stereocamera/test_titaniastereocamera.py
  test/unit/stereocamera/test_uvcstereocamera.py
  test/unit/stereomatcher/test_abstractstereomatcher.py
  test/unit/stereomatcher/test_stereobm.py
  test/unit/stereomatcher/test_stereoi3drsgm.py
  test/unit/stereomatcher/test_stereosgbm.py
  test/unit/test_utils.py
  test/unit/types/test_mat.py
  test/unit/types/test_stereo.py
Labels: enhancement

#47 added demo_titania_read
  .gitignore
  README.md
  test/data/titania_left.yaml
  test/data/titania_right.yaml
  test/drivers/demo_generate_pointcloud.py
  test/drivers/demo_match.py
  test/drivers/demo_match_thread.py
  test/drivers/demo_read.py
  test/drivers/demo_read_thread.py
  test/drivers/demo_titania_read.py
Labels: enhancement

#48 increase compute duration for unt test
  test/unit/stereomatcher/test_stereosgbm.py
Labels: bug

#50 tidied up comments and code
  test/drivers/demo_match_thread.py
  test/drivers/demo_read.py
Labels: enhancement

#51 added message to no save pointcloud
  test/drivers/demo_titania_read.py
Labels: enhancement

#52 rename 'drivers' folder to demo & update readmes
  README.md
  docs/README_developer.md
  test/demo/demo_generate_pointcloud.py
  test/demo/demo_match.py
  test/demo/demo_match_thread.py
  test/demo/demo_read.py
  test/demo/demo_read_thread.py
  test/demo/demo_titania_read.py
Labels: enhancement
